[aliases]

# usa
central = "america/chicago"
pacific = "america/los_angeles"
mountain = "america/boise"
eastern = "america/new_york"

# europe
brussels = "europe/brussels"
denmark = "europe/copenhagen"
portugal = "europe/lisbon"
paris = "europe/paris"
spain = "europe/madrid"
uk = "europe/london"
zagreb = "europe/zagreb"

# asia
hk = "asia/hong_kong"

# oceania
aet = "australia/sydney"
awt = "australia/perth"
nz = "pacific/auckland"
