backend = "fdo"
log-level = "debug"

[delete]
verbose = "on"

# For general behavior 'prompt' is probably what I want, but with --indices
# it seems unnecessary, and tedious. Hence 'prompt = "off"'.

[perm-delete]
indices = "on"
prompt = "off"
verbose = "on"

[restore]
indices = "on"
prompt = "off"
verbose = "on"
